### Reclamar un ingreso como médico
GET http://localhost:8080/ingresos/reclamar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIERldGFpbHMiLCJ1c2VybmFtZSI6Im1lZEBtYWlsLmNvbSIsImlhdCI6MTc2NTQ3MjcwNn0.C90YF7gk4C1qSvw0WfRlvJuNY5MSAKZgKGqSJi40l60

### Reclamar un ingreso como enfermero
GET http://localhost:8080/ingresos/reclamar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIERldGFpbHMiLCJ1c2VybmFtZSI6Im1lZEBtYWlsLmNvbSIsImlhdCI6MTc2NTQ3MjcwNn0.C90YF7gk4C1qSvw0WfRlvJuNY5MSAKZgKGqSJi40l60

### Ingresar informe como médico
POST http://localhost:8080/ingresos/informe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIERldGFpbHMiLCJ1c2VybmFtZSI6Im1lZEBtYWlsLmNvbSIsImlhdCI6MTc2NTQ3MjcwNn0.C90YF7gk4C1qSvw0WfRlvJuNY5MSAKZgKGqSJi40l60
Content-Type: application/json

{
  "informe": "Este informe fue escrito por un médico y es válido"
}
